---
abstract: 'Build and install the GNU Multiple Precision library'
author:
  - 'Richard Simões <rsimoes AT cpan DOT org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::Requires: 0
configure_requires:
  Archive::Tar: 0
  ExtUtils::CChecker: 0
  File::Spec: 0
  IPC::Cmd: 0
  Module::Build: 0.3601
  Net::FTP: 0
  perl: 5.010_001
  version: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-GMP
requires:
  File::ShareDir: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/rsimoes/alien-gmp/issues
  homepage: https://metacpan.org/release/Alien-GMP
  repository: git://github.com/rsimoes/alien-gmp.git
version: v0.0.1
